wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.2
    cli_version: 0.15.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1696242821.191754
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 14
      - 23
      4: 3.10.2
      5: 0.15.10
      8:
      - 3
      - 5
